name: Run prettier for WFH Application System to format frontend code after merge.

on:
  push:
    branches:
      - master

jobs:
  run_formatter:
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: backend

    steps:
      - name: Check out the code.
        uses: actions/checkout@v4.2.1

      - name: Set up NodeJS latest stable version.
        uses: actions/setup-node@v4.0.4
        with:
          node-version: 22.x

      - name: Install dependencies.
        run: |
          npm install --package-lock-only
          npm ci

      - name: Format the code.
        run: npm run prettier
