name: Run unit tests for WFH Application System backend.

on:
  pull_request:
    branches:
      - master

jobs:
  run_unit_tests:
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: backend

    steps:
      - name: Check out the code.
        uses: actions/checkout@v4.2.1
        with:
          fetch-depth: 0
          ref: ${{github.event.pull_request.head.ref}}
          repository: ${{github.event.pull_request.head.repo.full_name}}

      - name: Set up NodeJS latest stable version.
        uses: actions/setup-node@v3.8.2
        with:
          node-version: 22.x

      - name: Install dependencies.
        run: |
          npm install --package-lock-only
          npm ci

      - name: List scripts.
        run: npm run

      - name: Format the code.
        run: npm run prettier

      - name: Run the tests.
        run: npm run test
